# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 deploy:
    name: Build and Upload to Amazon S3
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2 
          
       - name: Install External Modules
         run: yarn install
       
       - name: Build
         run: CI=false yarn build
         
       - name: Upload Build Directory to Amazon S3
         run: aws s3 cp build s3://${{secrets.AWS_S3_BUCKET}} --recursive --acl public-read
